version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    # Added since golangci-lint v1.61.
    - embeddedstructfieldcheck
    - exhaustruct_v5
    - funcorder
    - gomodguard
    - modernize
    - noinlineerr
    - recvcheck
    - wsl_v5
  settings:
    goconst:
      min-len: 2
      min-occurrences: 4
    gosec:
      excludes:
        - G115
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    revive:
      enable-all-rules: false
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        text: fieldalignment
      - path: _test\.go
        linters:
          - goconst
      - path: tools/tester/main.go
        text: Error return value of `fmt\.Fprint.*` is not checked
      - path: (.+)\.go$
        text: Deferring unsafe method "Close" on type "io\.ReadCloser"
    paths:
      - dbg/dbg.go
      - token/token_const.go
      - terst
      - internal/regexp
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - dbg/dbg.go
      - token/token_const.go
      - terst
      - internal/regexp
      - third_party$
      - builtin$
      - examples$
